# Site settings
title: Recipes
description: >
  Collection of recipes.
baseurl: "/recipes" # the subpath of your site, e.g. /blog/
url: "http://kiranbot.com/recipes" # the base hostname & protocol for your site

# Build settings
markdown: kramdown
